# 张量的概念及基本运算

**张量是表示一个由数值组成的数组，这个数组可能存在多个维度**

## 张量的初始化

In [4]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape   #获取张量的形

torch.Size([12])

In [8]:
x.numel()   #获取张量中的元素总数

12

In [9]:
x = x.reshape(3,4)  #张量的形状调整
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.zeros((2,3,4))  #初始化一个全零的三维张量

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])  #手动初始化一个三维张量

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 张量的运算

In [13]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y,x - y,x * y,x / y,x ** y #求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
torch.exp(x)  #用于计算输入张量 x 中每个元素的指数（即 ( e^x )），其中 ( e ) 是自然对数的底数

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [15]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1) #在行和列上进行拼接

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
 x == y  #张量的逻辑运算，逐个元素对比

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
x.sum() #对张量的所有元素进行求和，只会产生一个只有一个元素的张量

tensor(66.)

**广播机制（broadcasting mechanism）导致的计算异常**

In [36]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [38]:
a + b  #形状不一样仍然计算成功  将a和b都按3x2进行计算

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [42]:
a = torch.arange(6).reshape((3,1,2))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[[0, 1]],
 
         [[2, 3]],
 
         [[4, 5]]]),
 tensor([[0, 1]]))

In [44]:
a + b 

tensor([[[0, 2]],

        [[2, 4]],

        [[4, 6]]])

## 元素访问

In [49]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
x[-1], x[1:3] #x的最后一行， x的第2到第3行

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [53]:
x[1,2] = 9 #将第二行第3列的元素赋值为9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [57]:
x[0:2, :] = 12  #选中第1行到第二行，所有列的元素，批量赋值为12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

**运行一些操作可能会导致内存的重新分配，在巨量数据的操作中应尽可能避免，减少内存拷贝的开销**

In [60]:
before = id(y)
y = y + x
id(y) == before  #这里的id类似于C/C++中的取地址，验证操作后的内存是不一样的

False

**执行原地操作**

In [65]:
z = torch.zeros_like(y)  #创建一个z，类型和y一致，但是元素全部初始化为0
print("id(z) == ", id(z))
z[:] = x = y              #直接对z的元素进行操作，不进行内存拷贝
print("id(z) == ", id(z))

id(z) ==  2673748111552
id(z) ==  2673748111552


In [69]:
#同样，对于后续计算不再需要变量的场景，可以直接修改原变量
before = id(x)
x += y
id(x) == before

True

## tensor转换

In [74]:
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [77]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)  #将大小为1的tensor转换为python的标量

(tensor([3.5000]), 3.5, 3.5, 3)