# 线性代数

**标量由只有一个元素的张量表示**

In [3]:
import torch

In [4]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

**可以将向量视为标量值组成的列表**

In [6]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [7]:
x[3]   #可通过张量的索引来访问任一元素

tensor(3)

In [8]:
len(x)  #获取张量的长度

4

In [9]:
x.shape #只有一个轴的张量，形状只有一个元素

torch.Size([4])

**创建矩阵**

In [11]:
A = torch.arange(20).reshape(5,4)  #创建一个5行四列的矩阵
B = torch.zeros(5,4)               #创建一个初始全零矩阵
A, B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

**矩阵的转置**

In [13]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

**对称矩阵**

In [15]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

**向量是标量的推广，矩阵是向量的推广一样，可以构建更多轴的数据结构**

X = torch.arange(24).reshape(2, 3, 4)
X

**给定具有相同形状的任何两个张量，任何二元运算的结果都是相同形状的张量**

In [19]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()  #分配新的内存，将A的副本拷贝进去
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

**两个矩阵的按元素乘法称为哈达玛积(不是矩阵的乘法)**

In [21]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

**矩阵元素的和**

In [23]:
 x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [24]:
A.shape, A.sum()  #不管矩阵的维度，矩阵元素的和始终是标量

(torch.Size([5, 4]), tensor(190.))

In [25]:
A_sum_axis0 = A.sum(axis=0)   #计算某个轴上的和，获取的是矩阵降维
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]))

In [26]:
A_sum_axis1 = A.sum(axis=[0, 1])   #计算多个轴上的和
A, A_sum_axis1, A_sum_axis1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor(190.),
 torch.Size([]))

**某些情况下计算总和或者某个轴上的和不希望轴数改变**

In [91]:
sum_A = A.sum(axis=0, keepdims=True)
sum_A

tensor([[40., 45., 50., 55.]])

**矩阵的2平均值**

In [30]:
A.mean(), A.sum() / A.numel()  #所有维度的均值

(tensor(9.5000), tensor(9.5000))

In [31]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]  #单个维度的均值

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

**点积**

In [59]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)  #向量的点积是一个标量

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

**举证向量积Ax是一个长度为m的列向量**

In [63]:
A.shape, x.shape, torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

**矩阵乘法**

In [66]:
B = torch.ones(4, 3)  #全1矩阵
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

**范数**

In [77]:
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum()   #L2范数所有元素求平方开根,L1范数绝对值求和

(tensor(5.), tensor(7.))

In [81]:
torch.norm(torch.ones((4,9)))    #矩阵的范数一般指F范数，即每个元素的平方和再开根

tensor(6.)