# 矩阵计算

**假设对函数  y = 2xTx 关于列向量x求导**

In [2]:
import torch

In [4]:
x = torch.arange(4.0)
x 

tensor([0., 1., 2., 3.])

In [13]:
x.requires_grad_(True)  # 申明需要求梯度后梯度保存的值空间  等价于 x = torch.arange(4.0, requires_grad=True)
x.grad  #后续可通过 x.grad 获取梯度，初始值是None

In [15]:
y = 2 * torch.dot(x,x)  # y关于x的函数定义

In [17]:
y.backward()    #调用反向传播计算y关于x每一个分量的梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [21]:
#y = 2xTx  的梯度应该为 2*2x = 4x
x.grad == 4*x

tensor([True, True, True, True])

**在默认情况下，pytorch会积累梯度，我们需要清除之前的值**

In [26]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

**深度学习中，我们的目的不是计算微分矩阵，而是批量中每个样本单独计算的偏导数之和**

In [ ]:
#对非标量调用‘backward'需要传入一个'gradient'参数，该参数指定微分函数关于self的梯度
x.grad.zero_()
y = x * x 